### ISSUE TITLE
Missing component components causing build issues

### ISSUE THREAD

**Issue by christopher-lamb** [HavenDV/HomeCenter.NET#7]
There are a couple components that are causing issues while building the solution:

* The missing **SharpShell** component in the **SearchDeskBand project** is causing build errors.
* The missing  **System.Net.Http** component in the **TelegramRunner project** is not causing any errors *(warning)* as it appears to not be used at the moment. Possibly remove or reinstall?

**Comment by HavenDV** [comment]
Fixed. Thank you
